/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TranscriptionId = IDL.Text;
export const LanguageCode = IDL.Text;
export const Time = IDL.Int;
export const TranscriptionRecord = IDL.Record({
  'id' : TranscriptionId,
  'source' : IDL.Text,
  'languageSource' : LanguageCode,
  'languageTarget' : LanguageCode,
  'translatedText' : IDL.Text,
  'timestamp' : Time,
  'transcriptText' : IDL.Text,
});
export const TranscriptionRecordInput = IDL.Record({
  'id' : TranscriptionId,
  'source' : IDL.Text,
  'languageSource' : LanguageCode,
  'languageTarget' : LanguageCode,
  'translatedText' : IDL.Text,
  'timestamp' : Time,
  'transcriptText' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearHistory' : IDL.Func([], [], []),
  'deleteTranscription' : IDL.Func([TranscriptionId], [], []),
  'getAllTranscriptions' : IDL.Func(
      [],
      [IDL.Vec(TranscriptionRecord)],
      ['query'],
    ),
  'saveTranscription' : IDL.Func([TranscriptionRecordInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TranscriptionId = IDL.Text;
  const LanguageCode = IDL.Text;
  const Time = IDL.Int;
  const TranscriptionRecord = IDL.Record({
    'id' : TranscriptionId,
    'source' : IDL.Text,
    'languageSource' : LanguageCode,
    'languageTarget' : LanguageCode,
    'translatedText' : IDL.Text,
    'timestamp' : Time,
    'transcriptText' : IDL.Text,
  });
  const TranscriptionRecordInput = IDL.Record({
    'id' : TranscriptionId,
    'source' : IDL.Text,
    'languageSource' : LanguageCode,
    'languageTarget' : LanguageCode,
    'translatedText' : IDL.Text,
    'timestamp' : Time,
    'transcriptText' : IDL.Text,
  });
  
  return IDL.Service({
    'clearHistory' : IDL.Func([], [], []),
    'deleteTranscription' : IDL.Func([TranscriptionId], [], []),
    'getAllTranscriptions' : IDL.Func(
        [],
        [IDL.Vec(TranscriptionRecord)],
        ['query'],
      ),
    'saveTranscription' : IDL.Func([TranscriptionRecordInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };